# ~/.config/starship.toml

# Don't print a new line at the start of the prompt
add_newline = false
# in milliseconds - 500 default - pyenv timesout quickly
# command_timeout = 10000
format = """
$all\
$fill\
$time\
$line_break\
$character
"""

[conda]
style = "dimmed green"
ignore_base = false

[nodejs]
symbol = "🌱 "

[fill]
symbol = " "

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

